### ISSUE TITLE
Proposition: setup the same label and milestones system as in stack repo

### ISSUE THREAD

**Issue by rvion** [haskell/haskell-ide-engine#22]
I suggest we use the same label system as for [stack](https://github.com/commercialhaskell/stack/issues) repo.

As of now, it's harder to understand where the project is going without them.

#### Milestones
https://github.com/commercialhaskell/stack/milestones
![image](https://cloud.githubusercontent.com/assets/2150990/10982872/0c241562-8410-11e5-9744-fb94a44f6961.png)

#### Labels
![image](https://cloud.githubusercontent.com/assets/2150990/10982907/2914cb62-8410-11e5-9922-ee542796838b.png)

- [x] copy-paste labels (keep color scheme)
- [x] create milestones
- [ ] tag existing issues with labels
- [x] give repo access to some people to speedup the tagging process

**Comment by mgsloan** [comment]
+1!

**Comment by bitemyapp** [comment]
:+1:

**Comment by alanz** [comment]
+1, @rvion I have added you to the project, can you do this?

**Comment by rvion** [comment]
Thanks, yes, I'll do this :)

**Comment by rvion** [comment]
I tweaked labels a little bit.
I also kept only 3 Milestones (I think that "Support" can either go in P1 or P2, and "Future" can go in P3)

**Comment by alanz** [comment]
Thanks. Is there documentation around the process we can bring over too?

**Comment by rvion** [comment]
I don't know. I don't think there is yet.
I plan to write some documentation soon (maybe this evening, I'm GMT +1 :) )
I also plan to make a few more changes in the readme, add contribution guidelines, etc.
I just can't do it right now cause I'm at work :)

**Comment by alanz** [comment]
Ok. I think https://github.com/commercialhaskell/stack/blob/master/CONTRIBUTING.md might be useful, and also to consider the process used in [haskell-mode](https://github.com/haskell/haskell-mode/wiki), but not using the wiki as people are more happy to engage if there is a PR for docs.

See also #13 cc @gracjan

**Comment by alanz** [comment]
I actually think I prefer "well defined task" to "help wanted"

**Comment by gracjan** [comment]
:+1: 

I would love labels to mean 'what is supposed to happen with this issue?'. So only labels that are actionable.

**Comment by alanz** [comment]
I also know that "well defined task" is a thing that haskell-mode uses to great effect to encourage initial contributions.

"help wanted" does not say anything about how difficult/complex the task is

**Comment by gracjan** [comment]
Well defined task has also this nice property that it forces project
leaders to actually write up properly what they want :)

**Comment by rvion** [comment]
ok, I'll switch it back this evening

**Comment by alanz** [comment]
thanks. just for the one?

**Comment by rvion** [comment]
yes, I just changed back the "Well defined task" to
![image](https://cloud.githubusercontent.com/assets/2150990/11003509/2c005834-84b3-11e5-8e1b-037e6721dbf0.png)
